### ISSUE TITLE
Installation issue: win7, 64bit

### ISSUE THREAD

**Issue by eucmanlee** [thiloklein/matchingMarkets#1]
Hi Thilo,

Thank you very much for your work. I just tried to put the new release on my machine to find following error message:

---

g++ -m32 -shared -s -static-libgcc -o matchingMarkets.dll tmp.def RcppExports.o stabitCpp.o stabitCpp2.o -LC:/PROGRA~1/R/R-32~1.3/bin/i386 -lRlapack -LC:/PROGRA~1/R/R-32~1.3/bin/i386 -lRblas -lgfortran -Ld:/RCompile/r-compiling/local/local323/lib/i386 -Ld:/RCompile/r-compiling/local/local323/lib -LC:/PROGRA~1/R/R-32~1.3/bin/i386 -lR
c:/rbuildtools/3.3/gcc-4.6.3/bin/../lib/gcc/i686-w64-mingw32/4.6.3/../../../../i686-w64-mingw32/bin/ld.exe: i386:x86-64 architecture of input file `RcppExports.o' is incompatible with i386 output
c:/rbuildtools/3.3/gcc-4.6.3/bin/../lib/gcc/i686-w64-mingw32/4.6.3/../../../../i686-w64-mingw32/bin/ld.exe: i386:x86-64 architecture of input file`stabitCpp.o' is incompatible with i386 output
c:/rbuildtools/3.3/gcc-4.6.3/bin/../lib/gcc/i686-w64-mingw32/4.6.3/../../../../i686-w64-mingw32/bin/ld.exe: i386:x86-64 architecture of input file `stabitCpp2.o' is incompatible with i386 output
Error: 64-bit reloc in dll
## ..

seems like R is trying to link some existing but incompatible libs. ?

Some advise?  

Best

Euc

**Comment by thiloklein** [comment]
Thanks for reporting, Euc. I just pushed a new version that should fix this. The issue was that R was attempting to link to the *.o files in my repo. For more info, see: http://lists.r-forge.r-project.org/pipermail/rcpp-devel/2014-June/007667.html

**Comment by eucmanlee** [comment]
Thank you Thilo,

Actually, I found that deleting those objs (i.e.  *.o ) under /src solves the issue.
So you may need to actually delete those files (e.g. stabitCpp.o) in the Git server subfolder. 
" .gitignore" seems good though..

Have a nice weekend :-)

Euc

**Comment by thiloklein** [comment]
Thanks, you too, Euc. I'm herewith closing the issue.
