### ISSUE TITLE
OpenMP support on macOS 10.13.4

### ISSUE THREAD

**Issue by Simon-Schulten** [thiloklein/matchingMarkets#11]
I had some trouble getting the developer version to work on macOS 10.13.4 due to missing OpenMP functionality even with Xcode and CommandLineTools installed.
Following a blog post I installed gfortran 6.1 and a clang4 version with OpenMP support and changed the Makevars file in my .R directory to

CC=/usr/local/clang4/bin/clang
CXX=/usr/local/clang4/bin/clang++
CXX11=/usr/local/clang4/bin/clang++
CXX14=/usr/local/clang4/bin/clang++
CXX17=/usr/local/clang4/bin/clang++
CXX1X=/usr/local/clang4/bin/clang++
LDFLAGS=-L/usr/local/clang4/lib

Now it works like a charm. Just wanted to leave this here in case someone else has similar trouble.

Blog post: https://thecoatlessprofessor.com/programming/openmp-in-r-on-os-x/#after-3-4-0
gfortran 6.1: https://gcc.gnu.org/wiki/GFortranBinaries#MacOS-11
clang4: https://uofi.app.box.com/v/r-macos-clang-pkg

**Comment by thiloklein** [comment]
Thanks for posting your solution!
