### ISSUE TITLE
Multiple Characteristics in the Valuation Equation

### ISSUE THREAD

**Issue by danielrs91** [thiloklein/matchingMarkets#12]
Hello Professor Klein,

I am a PhD student working on replicating Sørensen (2007) using stabit2, and I am having issues when I try to include multiple characteristics for each side of the market in the selection equation.  As of now, all I can do is use one for each side of the market.  I am relatively new to R, so this may be simple question.  Please let me know if you have an idea about the issue.  Thank you for your help and for developing the package.

Best,
Daniel Ripperger-Suhler

**Comment by thiloklein** [comment]
Thanks for positing this. From the information provided, I am unable to reproduce what you have done.

Here is an extension of the example in the ``stabit2`` help file -- see also https://matchingmarkets.org/stabit2.html -- for the case of two student and two college characteristics. I hope this helps.

> \## Simulate two-sided matching data
> xdata <- stabsim2(m=20, nStudents=100, nSlots=rep(5,20), verbose=FALSE,
>                   colleges = c("c1","c2"), students = c("s1","s2"),
>                   outcome = ~ c1:s1 + c2:s2 + eta + nu,
>                   selection = ~ -1 + c1:s1 + c2:s2 + eta
> )
> 
> \## Correction for sorting bias 
> fit2 <- stabit2(OUT = xdata$OUT,
>                 SEL = xdata$SEL,
>                 outcome = y ~ c1:s1 + c2:s2,
>                 selection = ~ -1 + c1:s1 + c2:s2,
>                 niter=1000
> )
