### ISSUE TITLE
Sorry, not ready to describe the issue yet.

### ISSUE THREAD

**Issue by vanderlindenma** [thiloklein/matchingMarkets#13]
Sorry, had posted an issue, but realized there is something fishy with how I got to my problem. I'll keep digging before maybe reposting the issue (not sure how to cancel an issue on my end).

**Comment by thiloklein** [comment]
OK Martin, closing this for now. Feel free to reopen any time.

**Comment by vanderlindenma** [comment]
Thanks Thilo. Sorry again, I really don't know what happen. My home computer (or myself) must have been having too many beers yesterday. Anyways, I am now on my computer at work and everything works fine. Sorry again for the bother.
