### ISSUE TITLE
Seed reset, again (for functions other than ttc2)

### ISSUE THREAD

**Issue by vanderlindenma** [thiloklein/matchingMarkets#15]
Running other simulations with "iaa" and it appears "iaa" also resets the seed on each run, just like described in https://github.com/thiloklein/matchingMarkets/issues/14 with respect to ttc2. 

I guess the "seed-setting" part of the code is present in most of the matching functions of the package. Unless this seed resetting is intended, it'd be great to change it in all the matching function (instead of in ttc2 only).

(Thanks to your very helpful assistance with https://github.com/thiloklein/matchingMarkets/issues/14, I know that I can use "seed = NULL" in the meantime, so no rush whatsoever.)

**Comment by thiloklein** [comment]
Thanks, not sure I understand your question. Working with the latest package version on GitHub and CRAN `matchingMarkets 1.0-1`, you should find that the default value for the seed argument is `NULL`.

Thus, every execution of the function is based on a different random number (seed). See the following:

> `> library(matchingMarkets)`
> `> iaa(nStudents=7, nSlots=c(3,3), acceptance="deferred")$matchings`
  college student
1       1       1
3       1       5
2       1       6
4       2       3
6       2       4
5       2       7
> `> runif(1)`
[1] 0.7533079
> `> iaa(nStudents=7, nSlots=c(3,3), acceptance="deferred")$matchings`
  college student
1       1       3
2       1       5
3       1       6
4       2       1
5       2       2
6       2       4
> `> runif(1)`
[1] 0.984957

**Comment by vanderlindenma** [comment]
Sorry about that, I must be working with an older version then. My bad, I'll try to remember to update to the latest release before posting a bug report next time (hopefully never :)).

**Comment by thiloklein** [comment]
Glad this helped and all the best for your research!
