### ISSUE TITLE
Returning error when there should be matches

### ISSUE THREAD

**Issue by zxtonizx** [thiloklein/matchingMarkets#16]
Thanks for a great package.

The preferences file attached produces an error. Am I missing something? Especially since 21 and 15 both list each other as first preferences.

FIle: [preferences.xlsx](https://github.com/thiloklein/matchingMarkets/files/3420038/preferences.xlsx)

```
library(readxl)
df <- read_excel("preferences.xlsx", sheet = 1)
sri(prefs = df)
```

Returns
```
Error in .jcall(hjw, "S", "sayHello", .jarray(instance)) : 
  java.lang.NumberFormatException: For input string: "NULL"
```
Same thing happens for simpler example on second tab. Use the following instead
`df <- read_excel("preferences.xlsx", sheet = 2)`

But oddly the simple version (and lots of other test sets) work on the R Shiny App I built.
Upload this file: [simple_preferences.xlsx](https://github.com/thiloklein/matchingMarkets/files/3420036/simple_preferences.xlsx)
Here: [https://zxtonizx.shinyapps.io/students/](url)

I did a lot of tweaking to get it to work if there were duplicates and with text verses numbers. However, still not clear on why the above phenomenon is happening, especially when you consider the simple example.

**Comment by thiloklein** [comment]
The `prefs` argument in function `sri()` requires a matrix as input - see the package documentation. 

Using `is.matrix(df)` you will find that `read_excel()` does not create a matrix but a list. Converting your preference matrix using `as.matrix()` gives the expected result.

Btw: Great to see your work on the shiny app and thanks for the credits! 

Cheers! Thilo
