### ISSUE TITLE
Non-NA preferences being dropped

### ISSUE THREAD

**Issue by yelmm** [thiloklein/matchingMarkets#19]
```
> s.prefs = matrix(c(rep(NA, 12), 1, 3, 2, rep(NA, 9)), ncol = 8)
> s.prefs
     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8]
[1,]   NA   NA   NA   NA    1   NA   NA   NA
[2,]   NA   NA   NA   NA    3   NA   NA   NA
[3,]   NA   NA   NA   NA    2   NA   NA   NA

> c.prefs = matrix(c(NA, NA, NA, NA, 1, 2, 3, NA, rep(NA, 8), NA, NA, NA, NA, NA, 1, NA, NA), ncol = 3)
> c.prefs
     [,1] [,2] [,3]
[1,]   NA   NA   NA
[2,]   NA   NA   NA
[3,]   NA   NA   NA
[4,]   NA   NA   NA
[5,]    1   NA   NA
[6,]    2   NA    1
[7,]    3   NA   NA
[8,]   NA   NA   NA

> hri(s.prefs = s.prefs, c.prefs = c.prefs)
[1] "Dropped s.prefs column(s): 1, 2, 3, 4, 5, 6, 7, 8"
[1] "Dropped c.prefs column(s): 1, 2, 3"
Error in `colnames<-`(`*tmp*`, value = s.names[colnames(s.prefs)]) : 
  attempt to set 'colnames' on an object with less than two dimensions
```
It seems that student 5 should apply to college 1 and be accepted, and both student 5's column in the student preference matrix as well as college 1's column in the college preference matrix are not all NAs, so I'm not sure why their columns are being dropped and resulting in this error. This seems like a bug.

Thank you!

**Comment by thiloklein** [comment]
To avoid confusion for yourself and others, please make sure to give the function documentation a proper read before using a package.

`c.prefs` :: matrix of dimension `nStudents` x `nColleges` with the `i`th column containing college i's ranking over students in decreasing order of  preference (i.e. most preferred first).

The specification of your `c.prefs` object is invalid. A column can never have `NA` before a student identifier.

In your example, student 5 ranks colleges 1, 2 and 3. But the student id 5 appears in none of the colleges' rankings.
