### ISSUE TITLE
error handling

### ISSUE THREAD

**Issue by eucmanlee** [thiloklein/matchingMarkets#2]
Hi K,

would you please look at the error message and help me to find out a potential issue here?

my c.id starts from 1 and goes upto 165 by one.
and s.id starts from 1 and goes upto 457 by one.

any comment would be appreciated. 

Best

Eucman
<-------------error messages ------------------------------------->

Drawing 1000 MCMC samples...
|----|----|----|----|----|----|----|----|----|----|

error: Mat::operator(): index out of bounds
**************************************************|
Error: Mat::operator(): index out of bounds
In addition: Warning messages:
1: In collegeId[[i]][j] <- which(H[[i]][, j] == 1) - 1 :
  number of items to replace is not a multiple of replacement length
2: In collegeId[[i]][j] <- which(H[[i]][, j] == 1) - 1 :
  number of items to replace is not a multiple of replacement length
3: In collegeId[[i]][j] <- which(H[[i]][, j] == 1) - 1 :
  number of items to replace is not a multiple of replacement length
4: In collegeId[[i]][j] <- which(H[[i]][, j] == 1) - 1 :
  number of items to replace is not a multiple of replacement length
5: In collegeId[[i]][j] <- which(H[[i]][, j] == 1) - 1 :
  number of items to replace is not a multiple of replacement length
6: In collegeId[[i]][j] <- which(H[[i]][, j] == 1) - 1 :
  number of items to replace is not a multiple of replacement length

**Comment by thiloklein** [comment]
Hi, please use the latest development version of the package on GitHub or R-Forge. The issue with version 0.2-1 on CRAN is that it requires observed matches to come first in the SEL argument. I'll push the latest R-Forge revision to CRAN with the next major release.
