### ISSUE TITLE
matchingMarkets archived on CRAN

### ISSUE THREAD

**Issue by zeileis** [thiloklein/matchingMarkets#20]
Thilo, I just noticed that your [matchingMarkets](https://CRAN.R-project.org/package=matchingMarkets) package was removed from CRAN today as [CRAN check errors](https://cran-archive.r-project.org/web/checks/2023/2023-04-05_check_results_matchingMarkets.html) were not addressed.

Do you plan to update the package and resubmit it to CRAN? That would be great!

**Comment by thiloklein** [comment]
Hi Achim - Thanks, the package is up on CRAN again. It took me some time to fix issue related to Mac and C++. The package now allows for case-insensitive file systems, such as Mac OS and is now also compatible with the compilers of more recent C++ versions.

**Comment by zeileis** [comment]
Great, thanks, reincluded in `Econometrics` and `Optimization` now.
