### ISSUE TITLE
id (m.id, c.id, s.id) specification for stabit2

### ISSUE THREAD

**Issue by eucmanlee** [thiloklein/matchingMarkets#3]
Hi Thilo,

It seems that we cannot specify the name of ids (m.id, c.id and s.id) in stabit2.

I have looked at the R code (stabit2.r) to find that when the 'stabit2' call  'stabit2_inner',
the m.id, c.id and s.id won't take the custom field name specified by the user. 

any thoughts?

**Comment by thiloklein** [comment]
Thanks very much for the pointer Eucman. I'll fix this with the next major release. For now, the simple fix on your side is to use the default id names.
