### ISSUE TITLE
College admission problem with incomplete lists

### ISSUE THREAD

**Issue by shyankirat** [thiloklein/matchingMarkets#4]
Hello Thilo,
I am using the package the college admission problem in one of my cases. Here the student matrix and college matrix have their own preferences. In some cases student might prefer only one of them and college also may not consider some students. In that case I tried to solve the issue by assigning 0 to such allocation. This caused assignment problem. Then I tried with NA and NULL too that also did not solve the issue. Can a modification me made where a student or college might not consider any option.  I have tried with the sample program that you have provided can you please provide some suggestions.

The code is also attached here 
daa(nStudents = 4, nSlots = c(1,2,2))
s.prefs<-matrix(c(3,1,2, 1,3,2, 1,0,2, 0,0,1), 3,4,dimnames = list(c("D1","D2","D3"),c("V1","V2","V3","V4")))
c.prefs<-matrix(c(0,3,1,2, 2,0,1,3, 2,1,3,4), 4,3,dimnames = list(c("V1","V2","V3","V4"),c("D1","D2","D3")))
daa(s.prefs=s.prefs, c.prefs=c.prefs, nSlots=c(1,2,2))

**Comment by thiloklein** [comment]
The problem you describe is the college admission problem with `incomplete lists`. That is, some students find certain colleges unacceptable and would rather not attend any college. This can be modelled by introducing an additional college (i.e. a non-college) with quota equal to the number of students. The idea is that you place preferences for the "non-college" before the non-acceptable choices.

Here is your example with "non-college" 4:

> nSlots <- c(1,2,2,4)
> (s.prefs <- matrix(c(2,3,1,4, 1,3,2,4, 1,3,4,2, 3,4,1,2), 4,4))

|  | [,1] | [,2] | [,3] | [,4] |
| :-: | :-: | :-: | :-: | :-: |
| [1,] | 2 | 1 | 1 | 3 |
| [2,] | 3 | 3 | 3 | 4 |
| [3,] | 1 | 2 | 4 | 1 |
| [4,] | 4 | 4 | 2 | 2 |

Student 3 would rather not attend a college than studying at college 2. Similarly, student 4 would rather not attend a college than studying at colleges 1 or 2. A similar solution can be implemented for `c.prefs` when a college finds certain students unacceptable.

**Comment by thiloklein** [comment]
**Update:** The college admission problem with `incomplete lists` is now implemented in the matchingMarkets package in function `hri`. See `?hri` for examples and the documentation.
