### ISSUE TITLE
rJava installation failure (-> matchingmarkets installation failure) on Mac OS Yosemite/ El Capitan

### ISSUE THREAD

**Issue by Leonardo-Vela** [thiloklein/matchingMarkets#8]
Hi all, 
I'm struggling when installing your matchingMarkets package in R on my Mac running on the latest version of El Capitan. The error message displays a Java VM installation failure but all my efforts to to solve this problem were unsuccessful. The problem seems to be related with a failure of my rJava package. I therefore tried uninstalling and installing Java again as well as reinstalling R twice.

It would be great if you had any tips or suggestions to help me use your R package.

Below I included my displayed error message: 

The downloaded binary packages are in
/var/folders/rm/zjr7h92d6jg9g0hsk84b2d1w0000gn/T//RtmppT45Dq/downloaded_packages
> library("rJava", lib.loc="/Library/Frameworks/R.framework/Versions/3.4/Resources/library")
Fehler: package or namespace load failed for ‘rJava’:
 .onLoad in loadNamespace() für 'rJava' fehlgeschlagen, Details:
  Aufruf: dyn.load(file, DLLpath = DLLpath, ...)
  Fehler: kann shared object '/Library/Frameworks/R.framework/Versions/3.4/Resources/library/rJava/libs/rJava.so' nicht laden:
  dlopen(/Library/Frameworks/R.framework/Versions/3.4/Resources/library/rJava/libs/rJava.so, 6): Library not loaded: @rpath/libjvm.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.4/Resources/library/rJava/libs/rJava.so
  Reason: image not found
> library("matchingMarkets", lib.loc="/Library/Frameworks/R.framework/Versions/3.4/Resources/library")
Fehler: package or namespace load failed for ‘matchingMarkets’:
 .onLoad in loadNamespace() für 'rJava' fehlgeschlagen, Details:
  Aufruf: dyn.load(file, DLLpath = DLLpath, ...)
  Fehler: kann shared object '/Library/Frameworks/R.framework/Versions/3.4/Resources/library/rJava/libs/rJava.so' nicht laden:
  dlopen(/Library/Frameworks/R.framework/Versions/3.4/Resources/library/rJava/libs/rJava.so, 6): Library not loaded: @rpath/libjvm.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.4/Resources/library/rJava/libs/rJava.so
  Reason: image not found

**Comment by svengiegerich** [comment]
It's a problem with the version of java the package **rJava** is using on mac. So you have to install an older version and tell R to use that version. 

First install 'Java for OS X 2017 - 01' at Apples site: https://support.apple.com/kb/DL1572?locale=de_DE
Then use your terminal:
```
sudo ln -s $(/usr/libexec/java_home)/jre/lib/server/libjvm.dylib /usr/local/lib
sudo R CMD javareconf
install.packages("rJava",type='source‘)
```

This should work. 
(eventually if you already have configured a custom libjvm (e.g. by an installed virtual machine) you have to rename this file and include it in javareconf)
