### ISSUE TITLE
Version of hri that gets input from csv files

### ISSUE THREAD

**Issue by bradbell** [thiloklein/matchingMarkets#9]
I am working on an R routine that reads csv files and uses matchingMarkets::hri to match navey officers to commands; similar to what the following package was doing
https://github.com/OuhscBbmc/usnavy-billets

Perhaps such a routine, (with officer, command changed to an abstraction that includes student,college) would be appropriate addition to the matchingMarkets project ?

You can find a preliminary version of the csv matching routine at
https://github.com/bradbell/match_csv

**Comment by thiloklein** [comment]
Thanks for the link to your project. I like this work a lot and can see how it is nicely complemeting the matchingMarkets package functionality.

**Comment by bradbell** [comment]
The match_cv project is in it's initial stages. I had some trouble using roxygen2 to document the project, so I went to using my OMhelp system
    https://github.com/bradbell/omhelp
which is easy for me because I use the same documentation for all languages.

If I do make an R package of this, or if you want to include it in matchingMarkets, the documentation will probably have to be converted.
